FROM docker.io/minio/minio:latest

RUN mkdir --parents /opt/app

COPY ./entrypoints/entrypoint_minio.sh /opt/app/entrypoint_minio.sh

COPY --from=docker.io/minio/mc:latest /usr/bin/mc /usr/bin/mc

RUN mkdir --parents /opt/app/data

RUN minio server /opt/app/data & \
    server_pid=$!; \
    until mc alias set minio http://localhost:9000 minioadmin minioadmin; do \
        sleep 1; \
    done; \
    mc mb minio/files; \
    kill $server_pid



