name: fastapi-docker-elk-grafana

services:
  minio:
    container_name: minio
    image: 'bitnami/minio:latest'
    env_file:
      - ./env_files/.env_minio.env
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./volumes/minio:/bitnami/minio/data
    networks:
      - api
    restart: always

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file:
      - ./env_files/.env_postgres.env
    ports:
      - "5432:5432"
    volumes:
       - ./volumes/postgres/data:/opt/app/data
    networks:
      - api
    restart: always

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.11
    env_file:
      - ./env_files/.env_pgadmin.env
    ports:
      - "5050:80"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - api
    restart: always
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    env_file:
      - ./env_files/.env_redis.env
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./volumes/redis/:/data
    networks:
      - api
    restart: always

networks:
  api:
    driver: bridge