"""init

Revision ID: 9e15bdaa7024
Revises: 
Create Date: 2024-09-29 15:35:23.707672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e15bdaa7024"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("create schema app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles_types",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_articles_types_description"),
        "articles_types",
        ["description"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_articles_types_id"),
        "articles_types",
        ["id"],
        unique=True,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_articles_types_name"),
        "articles_types",
        ["name"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "files_hashes",
        sa.Column("id", sa.TEXT(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_hashes_created_at"),
        "files_hashes",
        ["created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_hashes_id"),
        "files_hashes",
        ["id"],
        unique=True,
        schema="app",
    )
    op.create_table(
        "files_tree",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["app.files_tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_tree_created_at"),
        "files_tree",
        ["created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_tree_created_by"),
        "files_tree",
        ["created_by"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_tree_name"),
        "files_tree",
        ["name"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_tree_parent_id"),
        "files_tree",
        ["parent_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "archive_requests",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["app.files_tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_archive_requests_created_at"),
        "archive_requests",
        ["created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_archive_requests_created_by"),
        "archive_requests",
        ["created_by"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_archive_requests_id"),
        "archive_requests",
        ["id"],
        unique=True,
        schema="app",
    )
    op.create_table(
        "files",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("hash", sa.TEXT(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hash"],
            ["app.files_hashes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["app.files_tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_created_at"),
        "files",
        ["created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_created_by"),
        "files",
        ["created_by"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_id"), "files", ["id"], unique=True, schema="app"
    )
    op.create_index(
        op.f("ix_app_files_name"),
        "files",
        ["name"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_files_parent_id"),
        "files",
        ["parent_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "articles",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("icon", sa.UUID(), nullable=True),
        sa.Column("article_type", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_type"],
            ["app.articles_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["app.files_tree.id"],
        ),
        sa.ForeignKeyConstraint(
            ["icon"],
            ["app.files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_articles_content"),
        "articles",
        ["content"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_articles_created_at"),
        "articles",
        ["created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_articles_created_by"),
        "articles",
        ["created_by"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_articles_id"),
        "articles",
        ["id"],
        unique=True,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_articles_title"),
        "articles",
        ["title"],
        unique=False,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_app_articles_title"), table_name="articles", schema="app"
    )
    op.drop_index(
        op.f("ix_app_articles_id"), table_name="articles", schema="app"
    )
    op.drop_index(
        op.f("ix_app_articles_created_by"), table_name="articles", schema="app"
    )
    op.drop_index(
        op.f("ix_app_articles_created_at"), table_name="articles", schema="app"
    )
    op.drop_index(
        op.f("ix_app_articles_content"), table_name="articles", schema="app"
    )
    op.drop_table("articles", schema="app")
    op.drop_index(
        op.f("ix_app_files_parent_id"), table_name="files", schema="app"
    )
    op.drop_index(op.f("ix_app_files_name"), table_name="files", schema="app")
    op.drop_index(op.f("ix_app_files_id"), table_name="files", schema="app")
    op.drop_index(
        op.f("ix_app_files_created_by"), table_name="files", schema="app"
    )
    op.drop_index(
        op.f("ix_app_files_created_at"), table_name="files", schema="app"
    )
    op.drop_table("files", schema="app")
    op.drop_index(
        op.f("ix_app_archive_requests_id"),
        table_name="archive_requests",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_archive_requests_created_by"),
        table_name="archive_requests",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_archive_requests_created_at"),
        table_name="archive_requests",
        schema="app",
    )
    op.drop_table("archive_requests", schema="app")
    op.drop_index(
        op.f("ix_app_files_tree_parent_id"),
        table_name="files_tree",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_files_tree_name"), table_name="files_tree", schema="app"
    )
    op.drop_index(
        op.f("ix_app_files_tree_created_by"),
        table_name="files_tree",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_files_tree_created_at"),
        table_name="files_tree",
        schema="app",
    )
    op.drop_table("files_tree", schema="app")
    op.drop_index(
        op.f("ix_app_files_hashes_id"), table_name="files_hashes", schema="app"
    )
    op.drop_index(
        op.f("ix_app_files_hashes_created_at"),
        table_name="files_hashes",
        schema="app",
    )
    op.drop_table("files_hashes", schema="app")
    op.drop_index(
        op.f("ix_app_articles_types_name"),
        table_name="articles_types",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_articles_types_id"),
        table_name="articles_types",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_articles_types_description"),
        table_name="articles_types",
        schema="app",
    )
    op.drop_table("articles_types", schema="app")
    op.execute("drop schema app")
    # ### end Alembic commands ###
