"""changed_finished_at

Revision ID: 2f2a9f38af14
Revises: 639075823811
Create Date: 2024-08-31 19:59:59.433111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f2a9f38af14"
down_revision: Union[str, None] = "639075823811"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "archive_requests",
        "finished_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "archive_requests",
        "finished_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        schema="app",
    )
    # ### end Alembic commands ###
