"""added_archive_requests

Revision ID: 639075823811
Revises: 95f4647f53d7
Create Date: 2024-08-31 19:43:16.481537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "639075823811"
down_revision: Union[str, None] = "95f4647f53d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_requests",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("folder_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["app.files_tree.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_archive_requests_created_at"),
        "archive_requests",
        ["created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_archive_requests_created_by"),
        "archive_requests",
        ["created_by"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_archive_requests_id"),
        "archive_requests",
        ["id"],
        unique=True,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_app_archive_requests_id"),
        table_name="archive_requests",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_archive_requests_created_by"),
        table_name="archive_requests",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_archive_requests_created_at"),
        table_name="archive_requests",
        schema="app",
    )
    op.drop_table("archive_requests", schema="app")
    # ### end Alembic commands ###
