"""added_files_tree_and_articles

Revision ID: 95f4647f53d7
Revises: cca92e59030b
Create Date: 2024-08-31 00:13:33.291438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f4647f53d7'
down_revision: Union[str, None] = 'cca92e59030b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_tree',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['app.files_tree.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_files_tree_created_at'), 'files_tree', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_files_tree_created_by'), 'files_tree', ['created_by'], unique=False, schema='app')
    op.create_index(op.f('ix_app_files_tree_name'), 'files_tree', ['name'], unique=False, schema='app')
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['app.files_tree.id'], ),
    sa.ForeignKeyConstraint(['icon'], ['app.files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_articles_content'), 'articles', ['content'], unique=False, schema='app')
    op.create_index(op.f('ix_app_articles_created_at'), 'articles', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_articles_created_by'), 'articles', ['created_by'], unique=False, schema='app')
    op.create_index(op.f('ix_app_articles_id'), 'articles', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_articles_title'), 'articles', ['title'], unique=False, schema='app')
    op.add_column('files', sa.Column('parent_id', sa.Integer(), nullable=False), schema='app')
    op.add_column('files', sa.Column('created_by', sa.Text(), nullable=False), schema='app')
    op.create_index(op.f('ix_app_files_created_at'), 'files', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_files_created_by'), 'files', ['created_by'], unique=False, schema='app')
    op.create_foreign_key(None, 'files', 'files_tree', ['parent_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_index(op.f('ix_app_files_hashes_created_at'), 'files_hashes', ['created_at'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_files_hashes_created_at'), table_name='files_hashes', schema='app')
    op.drop_constraint(None, 'files', schema='app', type_='foreignkey')
    op.drop_index(op.f('ix_app_files_created_by'), table_name='files', schema='app')
    op.drop_index(op.f('ix_app_files_created_at'), table_name='files', schema='app')
    op.drop_column('files', 'created_by', schema='app')
    op.drop_column('files', 'parent_id', schema='app')
    op.drop_index(op.f('ix_app_articles_title'), table_name='articles', schema='app')
    op.drop_index(op.f('ix_app_articles_id'), table_name='articles', schema='app')
    op.drop_index(op.f('ix_app_articles_created_by'), table_name='articles', schema='app')
    op.drop_index(op.f('ix_app_articles_created_at'), table_name='articles', schema='app')
    op.drop_index(op.f('ix_app_articles_content'), table_name='articles', schema='app')
    op.drop_table('articles', schema='app')
    op.drop_index(op.f('ix_app_files_tree_name'), table_name='files_tree', schema='app')
    op.drop_index(op.f('ix_app_files_tree_created_by'), table_name='files_tree', schema='app')
    op.drop_index(op.f('ix_app_files_tree_created_at'), table_name='files_tree', schema='app')
    op.drop_table('files_tree', schema='app')
    # ### end Alembic commands ###
