"""init

Revision ID: cca92e59030b
Revises: 
Create Date: 2024-08-29 22:14:59.208311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca92e59030b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema app")
    op.create_table('files_hashes',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_files_hashes_id'), 'files_hashes', ['id'], unique=True, schema='app')
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('hash', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hash'], ['app.files_hashes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_files_id'), 'files', ['id'], unique=True, schema='app')
    op.create_index(op.f('ix_app_files_name'), 'files', ['name'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_files_name'), table_name='files', schema='app')
    op.drop_index(op.f('ix_app_files_id'), table_name='files', schema='app')
    op.drop_table('files', schema='app')
    op.drop_index(op.f('ix_app_files_hashes_id'), table_name='files_hashes', schema='app')
    op.drop_table('files_hashes', schema='app')
    # ### end Alembic commands ###
